<?php
require __DIR__ . '/config.php';
$u=require_user();$pdo=db();$q=trim($_GET['q']??'');$status=trim($_GET['status']??'');$trash=is_admin_general($u)&&($_GET['trash']??'')==='1';
$sql="SELECT a.*,o.protocol,o.team,u.bc_name AS creator_bc FROM aph_records a LEFT JOIN occurrences o ON o.id=a.occurrence_id LEFT JOIN users u ON u.id=a.created_by WHERE ".($trash?'a.deleted_at IS NOT NULL':'a.deleted_at IS NULL');$params=[];
if($q!==''){$sql.=" AND (a.code LIKE ? OR a.patient_name LIKE ? OR a.cns LIKE ? OR o.protocol LIKE ?)";$like="%$q%";$params=[$like,$like,$like,$like];}
if(!$trash&&in_array($status,['RASCUNHO','ARQUIVADA'],true)){$sql.=" AND a.status=?";$params[]=$status;}
if($u['role']==='CAMPO'&&!empty($u['team'])){$sql.=" AND (o.team=? OR o.team IS NULL OR o.team='')";$params[]=$u['team'];}
$sql.=" ORDER BY a.id DESC LIMIT 200";$st=$pdo->prepare($sql);$st->execute($params);$rows=$st->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(app_display_name())?> - Arquivo APH</title><link rel="stylesheet" href="assets/app.css"></head><body><button type="button" class="back-floating no-print" onclick="history.length>1?history.back():location.href='index.php'">← Voltar</button>
<header class="topbar"><div class="top-left"><img src="assets/logo_oficial_bombeiros.jpeg" class="logo-mini" alt="Logo"><div><strong><?=e(app_display_name())?></strong><span><?=$trash?'Lixeira de Fichas APH':'Arquivo de Fichas APH'?></span></div></div><div class="right"><a href="index.php">Operação</a><a href="aph.php">Nova APH</a><?php if(is_admin_general($u)):?><a href="aph_arquivo.php<?=$trash?'':'?trash=1'?>"><?=$trash?'Arquivo normal':'Lixeira'?></a><?php endif;?><a href="viaturas.php">Viaturas</a><a href="materiais.php">Materiais</a><a href="relatorios.php">Relatórios</a><a href="logout.php">Sair</a></div></header>
<main class="layout"><section class="card"><div class="section-head"><h2><?=$trash?'Fichas excluídas':'Fichas de Atendimento Pré-Hospitalar'?></h2><?php if(!$trash):?><a class="button-link" href="aph.php">+ Nova ficha</a><?php endif;?></div><form method="get" class="search-row"><?php if($trash):?><input type="hidden" name="trash" value="1"><?php endif;?><input name="q" value="<?=e($q)?>" placeholder="Buscar por APH, ocorrência, paciente ou CNS"><?php if(!$trash):?><select name="status"><option value="">Todos os status</option><option value="RASCUNHO" <?=$status==='RASCUNHO'?'selected':''?>>Rascunho</option><option value="ARQUIVADA" <?=$status==='ARQUIVADA'?'selected':''?>>Arquivada</option></select><?php endif;?><button>Buscar</button></form></section>
<section class="card table-wrap"><table><thead><tr><th>Ficha</th><th>Ocorrência</th><th>Paciente</th><th>CNS</th><th>Status</th><th>Equipe</th><th>Ações</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="7">Nenhuma ficha encontrada.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><strong><?=e($r['code'])?></strong></td><td><?=e($r['protocol']??'-')?></td><td><?=e($r['patient_name']??'-')?></td><td><?=e($r['cns']??'-')?></td><td><span class="badge"><?=$trash?'🗑️ EXCLUÍDA':($r['status']==='ARQUIVADA'?'🔒 ARQUIVADA':'📝 RASCUNHO')?></span></td><td><?=e($r['team']??'-')?></td><td><?php if(!$trash):?><a href="aph.php?id=<?=$r['id']?>">Abrir</a> · <a href="relatorio_aph.php?id=<?=$r['id']?>" target="_blank">Relatório</a> · <a href="aph_imprimir.php?id=<?=$r['id']?>" target="_blank">Imprimir</a><?php if(is_admin_general($u)):?> · <a class="danger-link" href="aph.php?id=<?=$r['id']?>#excluir">Excluir</a><?php endif;?><?php else:?><form method="post" action="aph_action.php" class="inline-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="justification" value="Restauração pela lixeira APH"><button>Restaurar</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></section></main><script src="assets/security.js"></script></body></html>
