<?php
require __DIR__ . '/config.php';$u=require_user();$pdo=db();$msg=$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!is_admin_general($u)){http_response_code(403);exit('Somente Admin Geral.');}
 if(!hash_equals(csrf_token(),$_POST['csrf']??''))exit('CSRF inválido');
 $name=trim($_POST['name']??'');$cat=trim($_POST['category']??'');$qty=(float)($_POST['quantity']??0);$min=(float)($_POST['minimum_quantity']??0);$unit=trim($_POST['unit']??'UN');$notes=trim($_POST['notes']??'');$just=trim($_POST['justification']??'');
 if($name===''||mb_strlen($just)<5)$err='Informe nome e justificativa.';
 else{try{$st=$pdo->prepare("INSERT INTO materials(name,category,quantity,minimum_quantity,unit,active,notes,updated_by,updated_at) VALUES(?,?,?,?,?,1,?,?,?) ON CONFLICT(name) DO UPDATE SET category=excluded.category,quantity=excluded.quantity,minimum_quantity=excluded.minimum_quantity,unit=excluded.unit,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=excluded.updated_at");$st->execute([$name,$cat?:null,$qty,$min,$unit?:'UN',$notes?:null,$u['id'],now_iso()]);admin_audit($pdo,$u['id'],'UPSERT','MATERIAL',$name,$just,'Quantidade: '.$qty);$msg='Material atualizado.';}catch(Throwable $e){$err='Erro ao salvar material.';}}
}
$rows=$pdo->query("SELECT * FROM materials WHERE active=1 ORDER BY category,name")->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Materiais - <?=e(app_display_name())?></title><link rel="stylesheet" href="assets/app.css"></head><body>
<button class="back-floating" onclick="history.back()">← Voltar</button><header class="topbar"><div class="top-left"><img src="assets/logo_oficial_bombeiros.jpeg" class="logo-mini"><div><strong><?=e(app_display_name())?></strong><span>Materiais e Estoque Operacional</span></div></div><div class="right"><a href="index.php">Operação</a><a href="logout.php">Sair</a></div></header>
<main class="layout"><?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<?php if(is_admin_general($u)):?><section class="card"><h2>Cadastrar / atualizar material</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="grid3"><label>Material<input name="name" required></label><label>Categoria<input name="category"></label><label>Unidade<input name="unit" value="UN"></label></div><div class="grid2"><label>Quantidade atual<input type="number" step="0.01" name="quantity" value="0"></label><label>Estoque mínimo<input type="number" step="0.01" name="minimum_quantity" value="0"></label></div><label>Observações<input name="notes"></label><label>Justificativa administrativa<input name="justification" required minlength="5"></label><button class="primary">Salvar material</button></form></section><?php endif;?>
<section class="card"><h2>Estoque</h2><div class="table-wrap"><table><thead><tr><th>Material</th><th>Categoria</th><th>Quantidade</th><th>Mínimo</th><th>Situação</th></tr></thead><tbody><?php foreach($rows as $r):$low=(float)$r['quantity']<=(float)$r['minimum_quantity'];?><tr class="<?=$low?'stock-low':''?>"><td><strong><?=e($r['name'])?></strong></td><td><?=e($r['category']?:'-')?></td><td><?=e((string)$r['quantity'].' '.$r['unit'])?></td><td><?=e((string)$r['minimum_quantity'].' '.$r['unit'])?></td><td><?=$low?'<span class="badge financial-bad">REPOR</span>':'<span class="badge financial-ok">OK</span>'?></td></tr><?php endforeach;?></tbody></table></div></section></main><script src="assets/security.js"></script></body></html>
