<?php
require __DIR__ . '/config.php';$u=require_user(['ADMIN','BASE','STAFF']);$pdo=db();
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');
$fromIso=$from.'T00:00:00';$toIso=$to.'T23:59:59';
$st=$pdo->prepare("SELECT * FROM occurrences WHERE created_at BETWEEN ? AND ? ORDER BY created_at DESC");$st->execute([$fromIso,$toIso]);$rows=$st->fetchAll();
$total=count($rows);$closed=count(array_filter($rows,fn($r)=>$r['status']==='ENCERRADA'));$critical=count(array_filter($rows,fn($r)=>$r['priority']==='CRITICA'));
$patientsSt=$pdo->prepare("SELECT COUNT(*) FROM aph_records WHERE deleted_at IS NULL AND created_at BETWEEN ? AND ?");$patientsSt->execute([$fromIso,$toIso]);$patients=(int)$patientsSt->fetchColumn();
$natures=[];$teams=[];$response=[];
foreach($rows as $r){$n=$r['nature']?:'SEM NATUREZA';$natures[$n]=($natures[$n]??0)+1;$t=$r['team']?:'SEM EQUIPE';$teams[$t]=($teams[$t]??0)+1;$m=minutes_between($r['requested_at']??($r['created_at']??null),$r['on_scene_at']??null);if($m!==null)$response[]=$m;}
arsort($natures);arsort($teams);$avgResponse=$response?round(array_sum($response)/count($response),1):null;$max=max(1,$total);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatórios - <?=e(app_display_name())?></title><link rel="stylesheet" href="assets/app.css"></head><body>
<button class="back-floating no-print" onclick="history.back()">← Voltar</button><header class="topbar"><div class="top-left"><img src="assets/logo_oficial_bombeiros.jpeg" class="logo-mini"><div><strong><?=e(app_display_name())?></strong><span>Relatórios Operacionais</span></div></div><div class="right"><a href="base.php">Central</a><button class="top-action" onclick="window.print()">🖨️ Imprimir</button><a href="logout.php">Sair</a></div></header>
<main class="layout"><section class="card no-print"><form method="get"><div class="grid3"><label>De<input type="date" name="from" value="<?=e($from)?>"></label><label>Até<input type="date" name="to" value="<?=e($to)?>"></label><label>&nbsp;<button class="primary">Gerar relatório</button></label></div></form></section>
<section class="kpi-grid"><article class="kpi"><span>Ocorrências</span><strong><?=$total?></strong></article><article class="kpi"><span>Encerradas</span><strong><?=$closed?></strong></article><article class="kpi kpi-critical"><span>Críticas</span><strong><?=$critical?></strong></article><article class="kpi"><span>Pacientes APH</span><strong><?=$patients?></strong></article><article class="kpi"><span>Tempo médio solicitação → local</span><strong><?=$avgResponse!==null?e((string)$avgResponse).' min':'—'?></strong></article></section>
<section class="detail-grid"><section class="card"><h2>Por natureza</h2><?php foreach($natures as $name=>$count):?><div class="report-row"><span><?=e($name)?></span><div class="report-bar"><i style="width:<?=round($count/$max*100)?>%"></i></div><strong><?=$count?></strong></div><?php endforeach;?></section><section class="card"><h2>Por equipe</h2><?php foreach($teams as $name=>$count):?><div class="report-row"><span><?=e($name)?></span><div class="report-bar"><i style="width:<?=round($count/$max*100)?>%"></i></div><strong><?=$count?></strong></div><?php endforeach;?></section></section>
<section class="card"><h2>Ocorrências do período</h2><div class="table-wrap"><table><thead><tr><th>Protocolo</th><th>Solicitação</th><th>Fechamento</th><th>Nível</th><th>Natureza / Tipo</th><th>Equipe</th><th>Status</th><th>Prioridade</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['protocol'])?></td><td><?=e(substr($r['requested_at']?:$r['created_at'],0,16))?></td><td><?=e($r['closed_at']?substr($r['closed_at'],0,16):'EM ANDAMENTO')?></td><td><?=e(occurrence_level_short($r['occurrence_level']??'NAO_CLASSIFICADO'))?></td><td><?=e(($r['nature']?:'').' / '.$r['type'])?></td><td><?=e($r['team']?:'-')?></td><td><?=e(occurrence_status_label($r['status']))?></td><td><?=e($r['priority'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</main><script src="assets/security.js"></script></body></html>
