<?php
require __DIR__ . '/config.php';
$u=require_user();$pdo=db();$id=(int)($_GET['id']??0);$r=load_aph($id);if(!$r||!empty($r['deleted_at'])){http_response_code(404);exit('Ficha não encontrada.');}if(!aph_can_access($u,$r)){http_response_code(403);exit('Acesso negado.');}
$d=json_decode($r['data_json']??'{}',true)?:[];
$occ=null;if(!empty($r['occurrence_id'])){$st=$pdo->prepare("SELECT * FROM occurrences WHERE id=?");$st->execute([$r['occurrence_id']]);$occ=$st->fetch()?:null;}
$s=$pdo->prepare("SELECT * FROM aph_signatures WHERE aph_id=? ORDER BY id");$s->execute([$id]);$sigs=$s->fetchAll();
function rv(array $d,string $k,string $fallback='não informado'): string{$v=trim((string)($d[$k]??''));return $v!==''?$v:$fallback;}
function human_date(string $x): string{if(!$x)return 'data não informada';$t=strtotime($x);return $t?date('d/m/Y',$t):$x;}
function pieces(array $items): string{$out=[];foreach($items as [$label,$value]){if(trim((string)$value)!=='')$out[]=$label.': '.$value;}return implode('; ',$out);}
$serviceDate=human_date((string)($d['service_date']??''));
$occText=$occ?($occ['protocol'].' — '.trim(($occ['nature']??'').' / '.($occ['type']??''),' /')):rv($d,'service_type');
$requestedAt=$occ['requested_at']??($occ['created_at']??'');$closedAt=$occ['closed_at']??'';$totalMinutes=minutes_between($requestedAt,$closedAt);$responseMinutes=minutes_between($requestedAt,$occ['on_scene_at']??null);
$initialVitals=pieces([['PA',$d['v1_bp']??''],['FC',$d['v1_hr']??''],['FR',$d['v1_rr']??''],['SpO₂',$d['v1_spo2']??''],['Temperatura',$d['v1_temp']??''],['Glicemia',$d['v1_glucose']??''],['Dor',$d['v1_pain']??'']]);
$lastVitals='';for($i=4;$i>=1;$i--){$v=pieces([['PA',$d["v{$i}_bp"]??''],['FC',$d["v{$i}_hr"]??''],['FR',$d["v{$i}_rr"]??''],['SpO₂',$d["v{$i}_spo2"]??''],['Temperatura',$d["v{$i}_temp"]??''],['Glicemia',$d["v{$i}_glucose"]??''],['Dor',$d["v{$i}_pain"]??'']]);if($v!==''){$lastVitals=$v;break;}}
$proc=[];$map=['proc_airway'=>'manejo básico de via aérea','proc_oxygen'=>'oxigênio suplementar','proc_bvm'=>'ventilação com BVM','proc_suction'=>'aspiração','proc_cpr'=>'RCP','proc_aed'=>'DEA/AED','proc_dressing'=>'curativo/compressão','proc_immobilization'=>'imobilização','proc_glucose'=>'glicemia capilar'];foreach($map as $k=>$label)if(!empty($d[$k]))$proc[]=$label;
$extra=trim((string)($d['report_additional_observations']??''));$extraEnabled=(($d['report_observation_page']??($extra!==''?'SIM':'NAO_HA'))==='SIM')&&$extra!=='';$base=system_setting('central_base_address','');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Relatório <?=e($r['code'])?></title><style>
*{box-sizing:border-box}body{font-family:Arial,sans-serif;background:#ddd;margin:0;color:#111}.toolbar{width:210mm;margin:8px auto;text-align:right}.toolbar button{width:auto;padding:10px 16px;border-radius:8px;font-weight:800}.back{background:#222;color:#fff;border:2px solid #f2b51d}.print{background:#a80e16;color:#fff;border:2px solid #f2b51d}.page{width:210mm;min-height:297mm;margin:8mm auto;background:#fff;padding:14mm 15mm;box-shadow:0 0 8px #777}.head{display:flex;align-items:center;gap:9mm;border-bottom:3px solid #a10f16;padding-bottom:5mm}.head img{width:26mm;height:26mm;object-fit:contain}.head h1{font-size:18px;color:#8b1118;margin:0}.head p{margin:1mm 0;font-size:9px}.code{margin-left:auto;text-align:right;font-size:9px}.block{margin-top:6mm}.block h2{font-size:11px;color:#7a0e14;border-bottom:1px solid #d6ae48;padding-bottom:1.5mm}.block p{font-size:10px;line-height:1.55;text-align:justify;margin:2.5mm 0}.facts{display:grid;grid-template-columns:1fr 1fr;gap:2mm 5mm;font-size:9px;background:#fff8e8;border:1px solid #e2c36f;padding:4mm}.facts b{color:#741016}.signs{display:grid;grid-template-columns:1fr 1fr;gap:5mm;margin-top:5mm}.sig{border-top:1px solid #555;padding-top:2mm;font-size:8px;text-align:center}.sig img{max-width:55mm;height:14mm;object-fit:contain}.notice{font-size:8px;background:#f3f3f3;padding:3mm;border-left:1mm solid #a10f16}.extra{white-space:pre-wrap;font-size:10px;line-height:1.7;border:1px solid #bbb;min-height:225mm;padding:6mm}.footer{margin-top:7mm;font-size:7.5px;color:#555}.pagebreak{page-break-before:always}@media print{body{background:white}.toolbar{display:none}.page{margin:0;box-shadow:none;width:auto;min-height:277mm;page-break-after:always}@page{size:A4;margin:0}}
</style></head><body><div class="toolbar"><button class="back" onclick="history.length>1?history.back():location.href='aph_arquivo.php'">← Voltar</button><button class="print" onclick="window.print()">🖨️ Imprimir / Salvar PDF</button></div>
<main class="page"><div class="head"><img src="assets/logo_oficial_bombeiros.jpeg" alt="Logo"><div><h1>RELATÓRIO AUTOMÁTICO DE ATENDIMENTO</h1><p><?=e(ORG_NAME)?></p><p><?=e(app_display_name())?> · Gerado a partir da Ficha APH</p><p>Base Central: <?=$base!==''?e($base):'_______________________________________________'?></p></div><div class="code"><strong><?=e($r['code'])?>-REL</strong><br>Ocorrência: <?=e($occ['protocol']??'—')?><br>Versão APH: <?=e((string)$r['version'])?></div></div>
<div class="notice"><strong>Conferência obrigatória:</strong> este relatório é montado automaticamente com os campos registrados na Ficha APH. Antes de imprimir, assinar ou arquivar, a equipe responsável deve conferir se o texto corresponde ao atendimento efetivamente realizado.</div>
<div class="block"><h2>1. Identificação resumida</h2><div class="facts"><div><b>Data:</b> <?=e($serviceDate)?></div><div><b>Natureza:</b> <?=e($occText)?></div><div><b>Local:</b> <?=e(rv($d,'scene_address',$occ['address']??'não informado'))?></div><div><b>Equipe:</b> <?=e(rv($d,'unit_team',$occ['team']??'não informada'))?></div><div><b>Paciente:</b> <?=e(rv($d,'patient_full_name'))?></div><div><b>Idade:</b> <?=e(rv($d,'patient_age'))?></div><div><b>Sexo:</b> <?=e(rv($d,'patient_sex'))?></div><div><b>Tipo sanguíneo informado:</b> <?=e(rv($d,'patient_blood_type','NÃO SABE'))?></div><div><b>CNS:</b> <?=e(rv($d,'patient_cns'))?></div><div><b>Acompanhante:</b> <?=e(rv($d,'responsible_name'))?></div><?php if($occ):?><div><b>Solicitação:</b> <?=e($requestedAt?:'—')?></div><div><b>Fechamento:</b> <?=e($closedAt?:'EM ANDAMENTO')?></div><div><b>Tempo solicitação → local:</b> <?=$responseMinutes!==null?e((string)$responseMinutes).' MIN':'—'?></div><div><b>Tempo total:</b> <?=$totalMinutes!==null?e((string)$totalMinutes).' MIN':'—'?></div><?php endif;?></div></div>
<div class="block"><h2>2. Relato automático do atendimento</h2><p>No dia <strong><?=e($serviceDate)?></strong>, a equipe <strong><?=e(rv($d,'unit_team',$occ['team']??'não informada'))?></strong> registrou atendimento referente à ocorrência <strong><?=e($occText)?></strong>, no local <strong><?=e(rv($d,'scene_address',$occ['address']??'não informado'))?></strong>. O paciente identificado como <strong><?=e(rv($d,'patient_full_name'))?></strong>, idade/idade aparente <strong><?=e(rv($d,'patient_age'))?></strong>, sexo informado <strong><?=e(rv($d,'patient_sex'))?></strong>, teve tipo sanguíneo informado como <strong><?=e(rv($d,'patient_blood_type','NÃO SABE'))?></strong>. A queixa principal registrada foi: <strong><?=e(rv($d,'chief_complaint'))?></strong>.</p>
<p>Na avaliação inicial foram registrados: X — <?=e(rv($d,'xabcde_x'))?>; A — <?=e(rv($d,'xabcde_a'))?>; B — <?=e(rv($d,'xabcde_b'))?>; C — <?=e(rv($d,'xabcde_c'))?>; D — <?=e(rv($d,'xabcde_d'))?>; E — <?=e(rv($d,'xabcde_e'))?>. Escala de Coma de Glasgow registrada: <strong><?=e(rv($d,'gcs_total'))?></strong>. Sinais vitais iniciais: <strong><?=e($initialVitals?:'não informados')?></strong><?php if($lastVitals!==''&&$lastVitals!==$initialVitals):?>. Último conjunto de sinais vitais registrado: <strong><?=e($lastVitals)?></strong><?php endif;?>.</p>
<p>Informações de história/avaliação registradas: sinais e sintomas — <?=e(rv($d,'sample_signs'))?>; alergias — <?=e(rv($d,'sample_allergies'))?>; medicamentos em uso — <?=e(rv($d,'sample_medications'))?>; passado médico — <?=e(rv($d,'sample_history'))?>; eventos relacionados — <?=e(rv($d,'sample_events'))?>.</p>
<p>Procedimentos/cuidados marcados na ficha: <strong><?=e($proc?implode(', ',$proc):'nenhum procedimento marcado')?></strong>. Detalhes adicionais: <?=e(rv($d,'procedure_other_details'))?>. Medicamentos administrados conforme registro: <?=e(rv($d,'medications_administered'))?>. Evolução: <?=e(rv($d,'evolution'))?>.</p>
<p>O desfecho registrado foi <strong><?=e(rv($d,'outcome'))?></strong>, com destino <strong><?=e(rv($d,'destination'))?></strong>. Passagem do caso/condições na entrega: <?=e(rv($d,'handover'))?>. Observações finais: <?=e(rv($d,'final_notes'))?>.</p></div>
<div class="block"><h2>3. Equipe responsável e assinaturas</h2><p><strong>Bombeiros/integrantes:</strong> <?=e(rv($d,'crew_members'))?><br><strong>Staff/plantão:</strong> <?=e(rv($d,'shift_staff'))?></p><div class="signs"><?php if(!$sigs):?><div class="sig">Nenhuma assinatura registrada na Ficha APH.</div><?php endif;?><?php foreach($sigs as $sg):?><div class="sig"><img src="signature_image.php?id=<?=$sg['id']?>" alt="Assinatura"><br><strong><?=e($sg['signer_bc_name']?:$sg['signer_name'])?></strong><br><?=e($sg['signature_capacity'])?> · <?=e($sg['signed_at'])?><br><?=$sg['valid']?'Assinatura válida para a versão':'Assinatura invalidada'?></div><?php endforeach;?></div></div>
<div class="footer">Relatório gerado automaticamente a partir do conteúdo da Ficha <?=e($r['code'])?> · Hash atual: <?=e($r['content_hash'])?></div></main>
<?php if($extraEnabled):?><section class="page pagebreak"><div class="head"><img src="assets/logo_oficial_bombeiros.jpeg" alt="Logo"><div><h1>OBSERVAÇÕES COMPLEMENTARES</h1><p><?=e($r['code'])?>-REL · Página adicional</p></div></div><div class="block"><h2>Observações registradas na Ficha APH</h2><div class="extra"><?=e($extra)?></div></div><div class="footer">Esta página integra o Relatório Automático vinculado à Ficha <?=e($r['code'])?>.</div></section><?php endif;?>
<script src="assets/security.js"></script></body></html>
